# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwdH4uIKjF4K5hfH_e0j_nRgnNKwSezp
"""

import streamlit as st
import pandas as pd
from datetime import date
from pymongo import MongoClient
from streamlit_calendar import calendar

# Load MongoDB connection details securely from .streamlit/secrets.toml
MONGO_URI = st.secrets["MONGO_URI"]  # Change to your MongoDB URI


# Connect to MongoDB
client = MongoClient(MONGO_URI)
db = client[mongo_db]
collection = db["leave_plans"]

st.title("Team Leave Planning Tool (MongoDB + Calendar)")

with st.form("Add Leave Plan"):
    name = st.text_input("Your Name")
    start_date = st.date_input("Leave Start Date", min_value=date.today())
    end_date = st.date_input("Leave End Date", min_value=start_date)
    leave_type = st.selectbox("Type of Leave", ["CL", "EL", "PL", "ML","Other(Mention in Reason)"])
    reason = st.text_area("Reason / Notes")
    submit = st.form_submit_button("Submit")

    if submit and name:
        collection.insert_one({
            "name": name,
            "start_date": str(start_date),
            "end_date": str(end_date),
            "type": leave_type,
            "reason": reason
        })
        st.success("Leave plan added!")

# Fetch all leave plans
leave_plans = list(collection.find({}))
if leave_plans:
    df = pd.DataFrame(leave_plans)
    df = df.drop(columns=["_id"]) if "_id" in df.columns else df
    st.subheader("All Planned Leaves")
    st.dataframe(df)

    # Format for calendar
    calendar_events = [
        {
            "title": f'{row["name"]} - {row["type"]}',
            "start": row["start_date"],
            "end": row["end_date"],
        }
        for _, row in df.iterrows()
    ]
    cal_options = {
        "initialView": "dayGridMonth",
        "editable": False,
    }
    calendar(events=calendar_events, options=cal_options, key="leave_calendar")
else:
    st.info("No leave plans submitted yet.")
